name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy project
        run: |
          set -e
          PROJECT_DIR="/var/www/project/cshd3"
          cd $PROJECT_DIR

          echo "Подтягиваем последний коммит..."
          git pull

          echo "Сборка и запуск контейнеров..."
          docker compose up --build -d

          echo "Устанавливаем зависимости и выполняем миграции..."
          docker compose exec backend composer install --no-interaction --prefer-dist --optimize-autoloader
          docker compose exec backend php artisan migrate --force
          
          echo "Deployment finished!"